In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
class MLP(nn.Module):
    def __init__(self, input_dims, hidden_dims, output_dims) -> None:
        super().__init__()
        self.linear1 = nn.Linear(input_dims, hidden_dims)
        self.linear2 = nn.Linear(hidden_dims, hidden_dims)
        self.output = nn.Linear(hidden_dims, output_dims)

    def forward(self, x):
        x = self.linear1(x)
        x = F.relu(x)
        x = self.linear2(x)
        x = F.relu(x)
        output = self.output(x)
        # Loại bỏ chiều dư thừa (chiều nào bằng 1 thì bỏ)
        return output.squeeze(1)

In [5]:
# TEST MODEL

input_dims = 9
hidden_dims = 64
output_dims = 1
batch_size = 2  # Số lượng mẫu trong batch

# Tạo dữ liệu đầu vào (batch_size x input_dims)
x = torch.randn(batch_size, input_dims)

# Khởi tạo mô hình và truyền đầu vào qua mô hình
model_test = MLP(input_dims, hidden_dims, output_dims)
output = model_test(x)

# In kết quả
print("Input: ", x)
print("Output: ", output)

Input:  tensor([[ 0.7580, -0.3075, -1.0812, -0.2021, -0.4499,  0.8572, -0.9408,  0.6023,
          1.6305],
        [-0.5905,  0.8994,  0.2108, -0.7351, -0.6002,  0.2306,  0.1573, -1.7813,
          0.8387]])
Output:  tensor([-0.1425, -0.2301], grad_fn=<SqueezeBackward1>)


In [12]:
lr = 1e-2
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model_test.parameters(), lr=lr)


x = torch.randn(2, 9)
y = torch.randn(2)

output = model_test.forward(x)
print(output)
output = model_test(x)
print(output)
loss = criterion(output, y)
print("Loss:", loss.item())

tensor([-0.1285, -0.0291], grad_fn=<SqueezeBackward1>)
tensor([-0.1285, -0.0291], grad_fn=<SqueezeBackward1>)
Loss: 0.38542574644088745


In [14]:
output.tolist()

[-0.12845873832702637, -0.029060930013656616]

In [9]:
import torch
import torch.nn as nn

# Mô hình đơn giản
class SimpleModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(10, 1)

    def forward(self, x):
        print("Forward method called")
        return self.linear(x)


model = SimpleModel()
x = torch.randn(5, 10)

# Gọi bằng model(x)
print("Using model(x):")
output = model(x)  # Gọi thông qua cơ chế PyTorch
print(output)

# Gọi trực tiếp model.forward(x)
print("\nUsing model.forward(x):")
output = model.forward(x)  # Gọi trực tiếp
print(output)

Using model(x):
Forward method called
tensor([[ 0.3481],
        [ 0.2654],
        [-1.2926],
        [-0.2435],
        [ 0.5492]], grad_fn=<AddmmBackward0>)

Using model.forward(x):
Forward method called
tensor([[ 0.3481],
        [ 0.2654],
        [-1.2926],
        [-0.2435],
        [ 0.5492]], grad_fn=<AddmmBackward0>)
