In [40]:
import numpy as np
import pandas as pd

In [41]:
def transform_X(X: np):
    N = len(X)
    # Thêm một cột toàn giá trị 1 vào phía trước của X
    X_b = np.c_[np.ones((N, 1)), X]
    
    return X_b

In [42]:
data = {
    'Experience': [3, 4, 5, 6],
    'Education': [12, 13, 14, 15],
    'Salary (million VND)': [60, 55, 66, 93]
}

df = pd.DataFrame(data).to_numpy()


In [43]:
X_b = transform_X(df[:, :2])
y = df[:, -1]

In [44]:
print(X_b)
print(y)

[[ 1.  3. 12.]
 [ 1.  4. 13.]
 [ 1.  5. 14.]
 [ 1.  6. 15.]]
[60 55 66 93]


In [45]:
import numpy as np

def predict(x_i, thetas):
    # xi: (N,3) ; thetas:(3,)
    y_hat = np.dot(x_i, thetas)
    # -> (N,)
    return y_hat


def compute_loss(y, y_hat):
    # y_hat : (N,)
    # y : (N,)
    return np.mean((y - y_hat) ** 2)  # Trung bình của các bình phương sai số


def derivate_loss(y, y_hat):
    # y_hat : (N,)
    # y : (N,)
    return 2 * (y_hat - y)


def derivative_thetas(x: np.ndarray, deriloss: np.ndarray):
    # deriloss shape : (N,)
    # x shape : (N, d)
    # Reshape deriloss to (N, 1) to match dimensions for matrix multiplication
    deriloss = deriloss.reshape(-1, 1)  # Shape (N, 1)
    # Compute gradient: (N, 1) * (N, d) -> (d,)
    theta_deri = np.dot(x.T, deriloss).flatten()  # Shape (d,)
    return theta_deri


def gradient_descent(X_b, y, n_epochs=50, learning_rate=0.01):
    # Initialize thetas: (3,)
    thetas = np.asarray([10, 3, 2])

    thetas_path = [thetas]
    losses = []

    for epoch in range(n_epochs):
        # compute output
        y_hat = predict(X_b, thetas)
        # shape (N,)
        loss = compute_loss(y, y_hat)
        # compute derivative of loss
        deri_loss = derivate_loss(y, y_hat)
        # compute derivative of parameters
        gradients = derivative_thetas(X_b, deri_loss)
        # update parameters
        thetas = thetas - (learning_rate * gradients)
        thetas_path.append(thetas)

        # Add the mean loss of the entire dataset
        losses.append(loss)
        print(f"Epoch {epoch+1}/{n_epochs}, Loss: {loss:.4f}")

    return thetas_path, losses

In [46]:
thetas = np.asarray([10, 3, 2])
print(thetas.reshape(-1, 1).shape)

(3, 1)


In [47]:
X_b = transform_X(df[:, :2])
y = df[:, -1]


mbgd_thetas, losses = gradient_descent(
    X_b, y, n_epochs=2, learning_rate=0.001)

print(mbgd_thetas)

Epoch 1/2, Loss: 433.0000
Epoch 2/2, Loss: 230.8771
[array([10,  3,  2]), array([10.144,  3.708,  4.004]), array([10.044928,  3.295056,  2.699408])]
